name: rentgo
description: RentGo mobile app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
